mybatis-plus:
  type-aliases-package: store.*.entity
  mapper-locations: classpath*:/mybatis/**/sqlMap/*Mapper.xml
  global-config:
    refresh: true #自动刷新xml配置文件
    db-config:
      field-strategy: not_null
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/morning?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      path:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    cluster:
      nodes:
  application:
    name: store-os-web
server:
  port: 8006
  error:
    path: /WEB-INF/views/common/404.jsp
  servlet:
    jsp:
      init-parameters:
        development: true

#  <mvc:annotation-driven enable-matrix-variables="true" />
#  <mvc:default-servlet-handler/>


