mybatis:
  type-aliases-package: store.os.entity
  mapper-locations: classpath:/mybatis/os/sqlMap/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/morning?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver