package store.product.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("os_category")
public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.category_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    @TableId
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.parent_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.name
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.sort
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.type
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.status
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.show_in_nav
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Byte showInNav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.show_in_top
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Byte showInTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.show_in_hot
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Byte showInHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.create_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.create_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.update_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.update_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.page_title
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String pageTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.page_description
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String pageDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.page_keyword
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String pageKeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_category.remarks
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Category(Long categoryId, Long parentId, String name, Integer sort, Byte type, Byte status, Byte showInNav, Byte showInTop, Byte showInHot, Date createTime, String createBy, Date updateTime, String updateBy, String pageTitle, String pageDescription, String pageKeyword, String remarks) {
        this.categoryId = categoryId;
        this.parentId = parentId;
        this.name = name;
        this.sort = sort;
        this.type = type;
        this.status = status;
        this.showInNav = showInNav;
        this.showInTop = showInTop;
        this.showInHot = showInHot;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
        this.pageTitle = pageTitle;
        this.pageDescription = pageDescription;
        this.pageKeyword = pageKeyword;
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.category_id
     *
     * @return the value of os_category.category_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.category_id
     *
     * @param categoryId the value for os_category.category_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.parent_id
     *
     * @return the value of os_category.parent_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.parent_id
     *
     * @param parentId the value for os_category.parent_id
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.name
     *
     * @return the value of os_category.name
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.name
     *
     * @param name the value for os_category.name
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.sort
     *
     * @return the value of os_category.sort
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.sort
     *
     * @param sort the value for os_category.sort
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.type
     *
     * @return the value of os_category.type
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.type
     *
     * @param type the value for os_category.type
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.status
     *
     * @return the value of os_category.status
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.status
     *
     * @param status the value for os_category.status
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.show_in_nav
     *
     * @return the value of os_category.show_in_nav
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Byte getShowInNav() {
        return showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.show_in_nav
     *
     * @param showInNav the value for os_category.show_in_nav
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setShowInNav(Byte showInNav) {
        this.showInNav = showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.show_in_top
     *
     * @return the value of os_category.show_in_top
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Byte getShowInTop() {
        return showInTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.show_in_top
     *
     * @param showInTop the value for os_category.show_in_top
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setShowInTop(Byte showInTop) {
        this.showInTop = showInTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.show_in_hot
     *
     * @return the value of os_category.show_in_hot
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Byte getShowInHot() {
        return showInHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.show_in_hot
     *
     * @param showInHot the value for os_category.show_in_hot
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setShowInHot(Byte showInHot) {
        this.showInHot = showInHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.create_time
     *
     * @return the value of os_category.create_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.create_time
     *
     * @param createTime the value for os_category.create_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.create_by
     *
     * @return the value of os_category.create_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.create_by
     *
     * @param createBy the value for os_category.create_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.update_time
     *
     * @return the value of os_category.update_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.update_time
     *
     * @param updateTime the value for os_category.update_time
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.update_by
     *
     * @return the value of os_category.update_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.update_by
     *
     * @param updateBy the value for os_category.update_by
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.page_title
     *
     * @return the value of os_category.page_title
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.page_title
     *
     * @param pageTitle the value for os_category.page_title
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle == null ? null : pageTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.page_description
     *
     * @return the value of os_category.page_description
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getPageDescription() {
        return pageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.page_description
     *
     * @param pageDescription the value for os_category.page_description
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setPageDescription(String pageDescription) {
        this.pageDescription = pageDescription == null ? null : pageDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.page_keyword
     *
     * @return the value of os_category.page_keyword
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getPageKeyword() {
        return pageKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.page_keyword
     *
     * @param pageKeyword the value for os_category.page_keyword
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setPageKeyword(String pageKeyword) {
        this.pageKeyword = pageKeyword == null ? null : pageKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_category.remarks
     *
     * @return the value of os_category.remarks
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_category.remarks
     *
     * @param remarks the value for os_category.remarks
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}