package store.product.mapper;

import store.product.entity.Category;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    Category selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_category
     *
     * @mbg.generated Wed Feb 27 20:00:00 CST 2019
     */
    int updateByPrimaryKey(Category record);
}